---
title: "SIGTURK 2026 Workshop"
description: "The Second Workshop on Natural Language Processing for Turkic Languages (SIGTURK 2026)"
draft: false
toc: true
images: []
contributors: []
---

== Call for Papers

SIGTURK— +
The Second Workshop on +
*Natural Language Processing for Turkic Languages* +
At EACL 2026

Rabat, Morocco +
March 28-29, 2026footnote:[Exact slot TBD.]

== Introduction

We are excited to announce the Second Meeting of the ACL Special
Interest Group on Turkic Languages, held in conjunction with The 19th
Conference of the European Chapter of the Association for Computational
Linguistics (EACL 2026), Rabat, Morocco.

Our primary aim is to provide a venue to foster research on
computational linguistics and natural language processing in Turkic
languages. By co-locating with EACL, we seek to facilitate interaction
among researchers from diverse backgrounds, encouraging the exchange of
ideas and the presentation of cutting-edge work in natural language
processing (NLP) specific to Turkic languages. The main objectives of
the workshop are:

* Promote the creation, curation, and evaluation of foundational
resources that will accelerate progress and enable reproducible research
for the entire Turkic language family, +
* Motivate and promote researchers from Turkic nations to attend
EACL/ACL and other related conferences and follow state-of-the-art
research and results on NLP and computational linguistics, +
* Host a shared task that establishes strong baselines and foster
collaboration on key challenges in Turkic NLP, +
* Provide a venue for discussing the formulation and analysis of NLP
models suitable for the typological features of Turkic languages, and +
* Strengthen collaborations between researchers in academia and industry
with an interest enlarging connections across the community and allow
rapid development of NLP methods and tools that are applicable to a wide
range of Turkic languages.

== Important Dates

* Direct paper submission deadline: December 19, 2025 +
* Pre-reviewed (ARR) submission deadline: January 2, 2026 +
* Notification of acceptance: January 23, 2026 +
* Camera-ready submission deadline: February 3, 2026 +
* Workshop date: March 28-29, 2026 +
* Note: All deadlines are 11:59 pm UTC -12h ("`anywhere on Earth`").

== Topics of interest

We invite submissions on all aspects Turkic computational linguistics
and NLP. Topics of interest include, but are not limited to:

* Creation and curation of datasets, corpora, and benchmarks for
monolingual or multilingual tasks in Turkic languages, +
* Studies on computational models for Turkic languages (morphology,
syntax, semantics). +
* Novel NLP applications of Turkic languages. +
* Software libraries, tools and large language models for Turkic NLP, +
* Proper evaluation of large-language models in Turkic languages, and +
* Cross-lingual transfer between Turkic languages or from/to
high-resource languages.

The workshop will also host a shared task on *Terminology-Aware Machine
Translation for English–Turkish Scientific Texts.* Details will be
posted at http://sigturk.org[sigturk.org] shortly.

=== Submissions

We invite novel research contributions as long papers following the EACL
2026 long paper format (anonymized with 8 pages excluding references and
an additional page for the camera-ready versions for the accepted
papers), and shared task system descriptions (4-6 pages excluding
references). Submissions should use the ACL Paper Styles available at
https://github.com/acl-org/acl-style-files (Latex and Word).

We will accept either direct submissions through our own submission
page, or submissions to the general ACL Rolling Review. Direct
submissions will be made via http://openreview.net[openreview.net]. The
exact URL will be available shortly at the workshop website link on
http://sigturk.org[sigturk.org].

All accepted papers will be published as part of our workshop
proceedings and will be presented either through oral presentations or
poster sessions.

=== Event details and registration

The workshop will be conducted in person at EACL and the presentation
will be held at Rabat, Morocco. Further details will come shortly.
Details regarding registration can be found on the main conference
website http://2026.eacl.org[2026.eacl.org] .

=== Organizers

Kemal Oflazer, Carnegie Mellon University, USA (General Chair) +
Abdullatif Köksal, Google DeepMind, UK (Program Committee Co-Chair) +
Onur Varol, Sabancı University, Turkey (Program Committee Co-Chair) +
Jonne Sälevä - Brandeis University, USA (Publicity Chair) +
Gözde Gül Şahin - Koç University, Turkey (Shared-Task Chair)

*Program Committee (confirmed):*

*Emre Can Açıkgöz*, University of Illinois Urbana-Champaign +
*Mehmet Fatih Amasyalı*, Yıldız Technical University +
*İnanç Arın*, Sabancı University +
*Nimet Beyza Bozdağ*, University of Illinois Urbana-Champaign +
*Cem Bozşahin*, Boğaziçi University +
*Necva Bölücü*, CSIRO +
*Çağrı Çöltekin*, University of Tübingen +
*Seza Doğruöz*, Ghent University +
*Gülşen Eryiğit*, Istanbul Technical University +
*Tunga Güngör*, Boğaziçi University +
*Dilek Hakkani-Tür,* University of Illinois, Urbana-Champaign +
J**afar Isbarov**, Virginia Tech +
*Dilara Keküllüoğlu*, Sabancı University +
*Aykut Koç*, Bilkent University +
*Murathan Kurfalı*, RISE Research Institutes of Sweden +
*Constantine Lignos*, Brandeis University +
*Arzucan Özgür*, Boğaziçi University +
*Adnan Öztürel*, Google +
*Anar Rzayev*, Institute of Science and Technology Austria (ISTA) +
*Lütfi Kerem Şenel*, TNG Technology Consulting +
*A. Cüneyd Tantuğ,* Istanbul Technical University +
*Çağrı Toraman*, Middle East Technical University +
*Gökhan Tür*, University of Illinois, Urbana-Champaign +
*Jonathan Washington*, Swarthmore College +
*Reyyan Yeniterzi*, GenAIus Technologies +
*Süveyda Yeniterzi*, GenAIus Technologies +
*Deniz Yuret*, Koç University +
*Kerem Zaman*, UNC-Chapel Hill +
*Deniz Zeyrek*, Boğaziçi University

== More information

For further details and updates, see http://sigturk.org[sigturk.org].
For any questions please send an email to sigturk.secretary@gmail.com .
